{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-qgate-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-qgate-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    {{- include "kube-qgate-operator.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.webhook.enabled }}
{{- if .Values.metrics.enabled }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-qgate-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-qgate-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "kube-qgate-operator.selectorLabels" . | nindent 4 }}
{{- end }}
