---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qgate.qgate.io
  resources:
  - qualitygatepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qgate.qgate.io
  resources:
  - qualitygatepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - qgate.qgate.io
  resources:
  - qualitygatepolicies/status
  verbs:
  - get
  - patch
  - update
