apiVersion: qgate.qgate.io/v1alpha1
kind: QualityGatePolicy
metadata:
  labels:
    app.kubernetes.io/name: kube-qgate-operator
    app.kubernetes.io/managed-by: kustomize
  name: qualitygatepolicy-sample
spec:
  selector:
    matchLabels:
      app: kube-qgate-operator
  sonarServer: http://localhost:9000
  projectKey: kube-qgate-operator
  mode: Audit
